##################################################
################ General Settings ################
##################################################

GeneralSettings:
  botToken: "WTFWTFWTFWTFWTFWTFWTFWTFWTFWTFWTF"

  noPermissionERROR: "You Have No Permission."
  helpBlockFooter: "Server Name"