##################################################
################ General Settings ################
##################################################

GeneralSettings:
  botToken: "WTFWTFWTFWTFWTFWTFWTFWTFWTFWTFWTF"